apiVersion: v1 
kind: Pod 
metadata:
  name: configmap-pod 
spec: 
  containers: 
  - name: test-container 
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  #what ever data present in dev-properties will be mounted in /etc/config
  volumes: 
    - name: config-volume 
      configMap:
        name: dev-properties 
  
  restartPolicy: Never