apiVersion: apps/v1
kind: Pod 
metadata:
  name: promethium-limit-request
spec:
  containers:
  - name: promethium-pods
    image: nginx
    resources:
      requests:
        memory: "64000Mi"
        cpu: "0.5"
      limits:
        memory: "128Mi"
        cpu: "1" 